### ISSUE TITLE
Return array type XML

### ISSUE THREAD

**Issue by imella** [inossidabile/wash_out#104]
Hi guys,

I have a question in terms of the generated XML when you have an array of values.

I have the following Reusable Type
#### Cmr::Interest

``` ruby
module Api
  class Cmr::Interest < WashOut::Type
    map name: :string

    def self.fetch experience
      experience.interests.map { |i| { interest: { name: i.name } } }
    end
  end
end
```
#### Cmr::Event

``` ruby
module Api
  class Cmr::Event < WashOut::Type
    map event_id: :integer, name: :string, interests: [interest: Api::Cmr::Interest]

    def self.fetch event_id
      event = Event.includes(experience: :interests).includes(:exchanges).find(event_id)
      experience = event.experience
      {
        value: {
          event_id: event.id,  name: experience.name, interests: Api::Cmr::Interest.fetch(experience)
        }
      }
    end
  end
```
#### Action

``` ruby
soap_action :get_event,
                :args => { :event_id => :integer },
                :return => Api::Cmr::Event
def get_event
  render soap: Api::Cmr::Event.fetch(params[:event_id])
end
```

I'm getting the following response using Savon

``` xml
<tns:GetEventResponse>
      <Value xsi:type="tns:Value">
        <EventId xsi:type="xsd:int">41</EventId>
        <Name xsi:type="xsd:string">2 entradas a Mundo Mágico</Name>
        <Interests xsi:type="tns:Interests">
          <Interest xsi:type="tns:Interest">
            <Name xsi:type="xsd:string">Social</Name>
          </Interest>
        </Interests>
        <Interests xsi:type="tns:Interests">
          <Interest xsi:type="tns:Interest">
            <Name xsi:type="xsd:string">Vida sana</Name>
          </Interest>
        </Interests>
      </Value>
</tns:GetEventResponse>
```

Maybe I'm doing something wrong but shouldn't the response be like these (the interests Part)

``` xml
<tns:GetEventResponse>
      <Value xsi:type="tns:Value">
        <EventId xsi:type="xsd:int">41</EventId>
        <Name xsi:type="xsd:string">2 entradas a Mundo Mágico</Name>
        <Interests xsi:type="tns:Interests">
          <Interest xsi:type="tns:Interest">
            <Name xsi:type="xsd:string">Social</Name>
          </Interest>
          <Interest xsi:type="tns:Interest">
            <Name xsi:type="xsd:string">Vida sana</Name>
          </Interest>
        </Interests>
      </Value>
</tns:GetEventResponse>
```

I'm totally a newbie writing SOAP Web services, it's my first attempt so probably I'm missing some things.

Hope you can help me,

Thanks!

**Comment by davebream** [comment]
@inossidabile After 4 years I'm coming back to this issue... 😄 

I don't think the answer was correct. If we define the structure like:

```
map(
  event_id: :integer,
  name: :string,
  interests: [interest: Api::Cmr::Interest]
)
```

then I would expect an `<Interests>` tag with multiple `<Interest>` elements. And no other child elements. I have a problem with a service that I'm trying to sync with. They're not able to parse and array of elements that is returned by `wash_out`.

**Comment by inossidabile** [comment]
What is returned exactly?

**Comment by davebream** [comment]
in my case it's

```
<Rooms>
  <Room>Room1</Room>
</Rooms>
<Rooms>
  <Room>Room2</Room>
</Rooms>
```

and I expect

```
<Rooms>
  <Room>Room1</Room>
  <Room>Room2</Room>
</Rooms>
```

**Comment by inossidabile** [comment]
The syntax `foo: [bar]` in wash out means that you want `foo to be array of bar`. What is array? Array is a data structure that has numerous entries of the same type. Up until here we are in sync.

What you don't seem to understand is that even in your example the first - is a correct example of `Rooms` as an array. And the second - is where you have `Room` that is an array. To understand why it's done this way imagine you'd need to actually make `Room` an array of basic type (a number maybe). But you can not put it as `<Room>1 ??? 2 ?? 3</Room>`.

Therefore as I already explained before - in XML an array is defined by multiplying the root-level tag many times. NOT ITS CHILDREN.

If you don't agree please reread both explanations again ;).
