### ISSUE TITLE
Multiple SOAP services with different namespaces

### ISSUE THREAD

**Issue by mhenrixon** [inossidabile/wash_out#108]
Hi,

Was browsing around for a way to set the namespace in the controller rather than the environment config since I have multiple SOAP services that require their own namespace. Suggestions?

Also Would it be possible to verify the WSDL against an existing WSDL file to make sure they look alike?

**Comment by cartasu** [comment]
I've just actualized all gems rails ruby etc... ran into the same problem
´´´No route matches {:action=>"_action"´´´
any supportiv guesses?
