### ISSUE TITLE
Params not being populated

### ISSUE THREAD

**Issue by cjmendoza** [inossidabile/wash_out#155]
I am using rails 4 and ruby 2.1.0.  My controller looks as follows:
class CcdExchangeController < ApplicationController
  soap_service namespace: 'urn:WashOut', wsdl_style: 'document'

  soap_action "ccd_info",
              :args => {:pat_id => :string, :from_date => :string, :to_date => :string},
              :return => :string
  def ccd_info
    render :soap => "list_of_ccds for pat_id:#{params}"
  end

  soap_action "ccd_get",
              :args => {pat_id: :string, ccd_id: :string},
              :return => :string
  def ccd_get
  end

  soap_action "ccd_put",
              :args => {pat_id: :string},
              :return => :string
  def ccd_put
  end
end

When I   result = client.call(:ccd_info, message: { :pat_id => '12345' , :from_date=>"today", :to_date=>"today"})

I do not get the params populated in the method.
Any ideas? Thanks in advance.

**Comment by jonasbring** [comment]
Ran in to this when upgrading from rails 3.2 to 4. Any solutions?

**Comment by guivinicius** [comment]
I had a similar problem here, but I solved using **lowerCamelCase** on my args names. 

Like 

```ruby
args: { patId: :string, fromDate: :date }
```

**Comment by cjmendoza** [comment]
Thank you.Claudio J. Mendoza305.606.1126www.mendoxa.com


-------- Original Message --------
Subject: Re: [wash_out] Params not being populated (#155)

**Comment by harold-s** [comment]
Hello,

I have the same problem here.

Rails 4.2.0
wash_out 0.9.2
ruby 2.1.2p95

Any keys in camelcase or snakecase are strippeds.

If you want to make it work, remove them.

Don't really know where to start to debug the problem on this project. My SOAP need being specific I currently parse the raw POST data :

Hash.from_xml(request.raw_post)

Security has to be checked

**Comment by cartasu** [comment]
Hi there,
I've got the same problem, in my controller i don't receive any value from SoapUI. The request is received and, if I give set an Id (the param) a response is sent.

Like so, I get an error ```couldn't find without an id```
and if I do ```id = params[:value].to_i``` it converts to [0] -> is empty
```
class PlentyController < ApplicationController
  before_filter :dump_parameters
   soap_service namespace: 'urn:WashOut', wsse_auth_callback: ->(username, password) {
  return !User.find_by(email: username).authenticate(password).blank?
}

  soap_action "getspare",
              :args   => :integer,
              :return => :array
  def getspare
id = params[:value]
@spares = Spare.find(id)
data = [ @spares.id, @spares.part_id]

    render :soap => data
  end

  def dump_parameters

    logger.debug params.inspect
  end
end
``` 
    If I set a fixed id like
```
@spares = Spare.find(234)
```
I receive a response at least...
but that's not what it should be...isn't it?

For all I've read up till now it seems to be some issues with nokogiri
please help

**Comment by klenwell** [comment]
I was testing my controller using method described [here](http://blog.johnsonch.com/2013/04/18/rails-3-soap-and-testing-oh-my/) and found params sent by Savon client missing in my Wash Out controller. 

Comment by @harold-s helped me resolve the issue.To reiterate: be careful using symbols for message keys in Savon. Savon will convert symbols to camel-case strings.

**Comment by inossidabile** [comment]
Just a short summary of a whole thread: be careful debugging your app. Period.

**Comment by AbhisekGIT** [comment]
> I had a similar problem here, but I solved using **lowerCamelCase** on my args names.
> 
> Like
> 
> ```ruby
> args: { patId: :string, fromDate: :date }
> ```

Never expected this silly reason would be such a pain to debug. Thanks a ton
