### ISSUE TITLE
Reading/Writing SOAP headers

### ISSUE THREAD

**Issue by mathiasAichinger** [inossidabile/wash_out#157]
Hi,
I have an use-case where I have to read/write tags into the `<soap:Header>`. Is there a way to do this with wash_out?

**Comment by CloCkWeRX** [comment]
A pull request + tests would be handy

**Comment by Syfer** [comment]
Any updates for this issue ?

**Comment by rauluranga** [comment]
Hi!
Is there Any updates for this?
i'm also need to read Header information.

**Comment by rauluranga** [comment]
i know i'm cheating but right now i'm reading this information from the `request.request_parameters`

**Comment by yjukaku** [comment]
So... any progress?

**Comment by mathiasAichinger** [comment]
Sry, totally forgot about this issue :( @yjukaku  it looks like you already solved it and also created tests. can you open the PR?

**Comment by yjukaku** [comment]
There has been a PR open, just waiting on a merge. I no longer work on the project that I needed this library for, so I'm not sure I'll be able to continue working on this.

**Comment by inossidabile** [comment]
Merged.
