### ISSUE TITLE
Application Error: Duplicate use of `XXXX` type name. Consider using classified types.

### ISSUE THREAD

**Issue by shiju-d** [inossidabile/wash_out#158]
Hi,

Getting _"Application Error: Duplicate use of `ResponseHeader` type name. Consider using classified types."_ when I am trying to render to different soap actions with same response header. Please help me out to tackle this issue.

Action 1
soap_action 'action1',
    args: {
      apiUser: :string,
      apiPass: :string
    },
    return: {
      action1result: {
        response_header:{
          err_no: :string,
          err_no_desc: :string
        },
        results: {
        }
      }
    },
    to: :get_action1

---

Action2
soap_action 'action2',
    args: {
      apiUser: :string,
      apiPass: :string
    },
    return: {
      action2result: {
        response_header:{
          err_no: :string,
          err_no_desc: :string
        },
        results: {
        }
      }
    },
    to: :get_action2

Thanks.

**Comment by CR4567** [comment]
Hey,

how did you handle this? I have the same problem. 
Did you use the WashOut Types?

**Comment by Ramanpreetsingh** [comment]
Did anyone find a solution to this issue? I'm also facing this issue.

**Comment by CR4567** [comment]
No I didn't find a perfect solution. But in my case I figured out that the api is working and it's just a problem for the wsdl builder.

**Comment by Ramanpreetsingh** [comment]
Okay. Can you look into this issue : https://github.com/inossidabile/wash_out/issues/251

**Comment by Ramanpreetsingh** [comment]
To call the API from Savon (SOAP UI or any other client), initially GET wsdl action is invoked, and it throws an error there if you have any duplicate usage. How can you expect it to work when you are calling the API?

**Comment by CR4567** [comment]
ok my example is a little bit different.. I'm using it for the connection to an external service provider.
So I get a wsdl file from him, which I use as reference. So I don't you the one that wash_out is generating. Because that's not working the way I would expect it. 

That's a really bad fix especially if you want to generate your own api but it's working at least.

Sorry can't give you a better fix right now.
I'm sure there is a way to fix it with wash_out but I didn't figure out how....

**Comment by CR4567** [comment]
if you need further help it would be a good idea to open a new ticket for this ...
I don't think that anyone else will find it right now.
