### ISSUE TITLE
Custom XML Property 

### ISSUE THREAD

**Issue by nithinstany** [inossidabile/wash_out#164]
HI,

   "How can i set ' RoomType RoomCode="SGL"' like this in wash_out GEM

 
  MyResponse
     RoomTypes
        RoomType RoomCode="SGL"
           RoomDescription Name="Single Room"
              Text>One King Bedroom</Text
           /RoomDescription
        /RoomType
     /RoomTypes
  /MyResponse

**Comment by inossidabile** [comment]
There's no direct way to do that and I have no idea why you might want that. SOAP doesn't expect you to know what's hapenning on the transport level. Combined with the fact features are currently frozen for this project (unfortunately I don't have any time to work with it) I have to just close this. Pull-requests are welcome.
