### ISSUE TITLE
RSpec doesn't see wash_out routes

### ISSUE THREAD

**Issue by hexdigest** [inossidabile/wash_out#172]
Hi,

I'm trying to write test for my wash_out based controller:

```
require "spec_helper"

describe TestSoapController do
  it "should be fine" do
    post_data = %{       
      <?xml version="1.0" encoding="UTF-8"?>
      <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://someuri">
       <SOAP-ENV:Body>
       <ns1:TestMethod>
        <ns1:FirstParam>16593</ns1:FirstParam>
        <ns1:SecondParam>16593</ns1:SecondParam>
       </ns1:TestMethod>
       </SOAP-ENV:Body>
      </SOAP-ENV:Envelope>
    }

    post :action, {}, {
      "CONTENT_TYPE" => 'application/xml',
      "RAW_POST_DATA" => post_data
    }
  end
end
```

RSpec produces:
```
ActionController::RoutingError:
       No route matches {:controller=>"test_soap", :action=>"action"}
```

Is there any way to make such kind of test running without using Savon and mocking HTTPI?
How to make RSpec to see this route?

**Comment by wethu** [comment]
Hey, yeah same problem, didn't by any chance find a work around? Im just using request specs at the moment, but really would love a controller context..

**Comment by inossidabile** [comment]
Yes. You can add normal routes additionally to what WashOut provides. You can actually do that for test environment only for secure purposes.
