### ISSUE TITLE
Rails Engine ActiveRecord models aren't descendants of WashOut::Type

### ISSUE THREAD

**Issue by jnathanh** [inossidabile/wash_out#181]
I am trying to return an ActiveRecord object, whose model is defined in an engine:
```ruby
	soap_action "get_company",
		:return => MyTableEngine::Company
	def get_company
		render soap: MyTableEngine::Company.first
	end
```
But it is not recognizing that model as a WashOut::Type.  From what I understand of the documentation, that should be a valid use case:

"Note that WashOut extends the ActiveRecord so every model you use is already a WashOut::Type and can be used inside your interface declarations."

When I check to see if ActiveRecord::Base inherits from WashOut::Type it doesn't:
```ruby
ActiveRecord::Base.ancestors.include? WashOut::Type # => false
```
Maybe I'm just not doing it right, but I feel like I'm following the documentation. Is this a bug in the gem, or am I not understanding the documentation correctly?

**Comment by inossidabile** [comment]
They are not. But they are extending the same `WashOut::Model` module.
