### ISSUE TITLE
undefined method `washout_namespace=' for ActionView::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by iashanmugavel** [inossidabile/wash_out#187]
Hi, 

I have upgraded `wash_out` gem from `-v0.7.1` to  `-v0.9.2` in rails 4.2.3 application,

Based on post installation instruction, 

 Please replace `include WashOut::SOAP` with `soap_service`
    in your controllers if you are upgrading from a version before 0.8.5.

replaced with `include WashOut::SOAP` with `soap_service`.

now while starting rails server, it breaks with the following error.

```
/usr/local/rvm/gems/ruby-2.2.2/gems/actionview-4.2.3/lib/action_view/railtie.rb:26:in `block (3 levels) in <class:Railtie>': undefined method `washout_namespace=' for ActionView::Base:Class (NoMethodError)
```

My Controller,

```ruby
class Api::Soap::UnionWsController < ApplicationController
  #include WashOut::SOAP 
soap_service namespace: 'urn:WashOut'
  soap_action "upload_student",
              :args   => {}
end
```

routes.rb

```ruby 
Rails.application.routes.draw do
  wash_out :'api/soap/union_ws'
end
```

How to fix this issue.

**Comment by inossidabile** [comment]
Please read the new syntax in README carefully. You are clearly using the old one in calling `self.washout_namespace =` which is not working anymore.
