### ISSUE TITLE
undefined method `values_at' for nil:NilClass while

### ISSUE THREAD

**Issue by rauluranga** [inossidabile/wash_out#188]
I'm getting the following error:
```html
<h1>
  NoMethodError
    in FaultserviceController#_action
</h1>
<pre>undefined method `values_at&#x27; for nil:NilClass</pre>
```
the request XML looks like the following:

```XML
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/">
  <x:Header/>
  <x:Body/>
</x:Envelope>
```
I'm using RestInSoap Chrome Extension for testing.

**Comment by rauluranga** [comment]
ok
I figured out was was causing the problem.
RestInSoap was sending the action name in the Request Headers (unknown by wash_out)

so the XML should  look like

```xml
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/">
  <x:Header/>
  <x:Body>
<x:Body xmlns:m="http://www.example.org/stock">
  <m:ACTION_NAME>
  </m:ACTION_NAME>
  </x:Body>
</x:Envelope>
```
`ACTION_NAME` is the request sent to the server, and that's it.

**Comment by inossidabile** [comment]
It does look for SOAPAction in the header. It's not something that's optional – it's the main way to figure out the requested action. Nevertheless the body _has_ to contain same method as a tag. It can't be empty according to standard. And the answer is no – I don't thin we should support buggy clients.
