### ISSUE TITLE
Rails 5 API mode compatibility

### ISSUE THREAD

**Issue by mhutter** [inossidabile/wash_out#191]
- [ ] include in `ActionController::Metal` instead of `ActionController::Base`
- [ ] only disable `before_action :validate_authenticity_token` when present (leads to errors otherwise)
- [ ] fix problem with `helper`

Rails 5 Applications in API mode subclass `ApplicationController` from `ActionController::API` instead of `ActionController::Base`. This has some consequences:
- `ActionController::API` is not subclassed from `ActionController::Base`
- `ActionController::API` does not have the `helpers` method
- `ActionController::API` does as per default not have the `:validate_authenticity_token` callback enabled

**Comment by inossidabile** [comment]
And this is needed because?.. :) Aren't you missing compatibility with enhancing? Yes, I know `rails-api` has been merged in. And we better switch to that in future. How is that related to _compatibility_ though? We do have Rails 5 in building matrix and tests pass.

**Comment by mhutter** [comment]
This is a feature request/proposal, not a bug report.

It's needed because the gem won't work with Rails 5 apps in API mode - which would be nice! :)

I created this issue to document what I already learned. I intended to fix it myself but I don't have the time right now (maybe next month when I will implement a project using this gem), but maybe others are interested in this aswell.

**Comment by Envek** [comment]
+1 on this. We're using Rails 4.2 in API mode and need to do hacks like https://github.com/Envek/wash_out/commit/bbe07fd6fbbfd61f6a583b8be41f5a261387f36c to get things working (or just switch off api_only mode and subclass directly from `ActiveRecord::Base`).

**Comment by merhard** [comment]
@mhutter I submitted a pull request for this feature request/proposal. Let me know if it is what you had in mind.
