### ISSUE TITLE
WSDL doesn't work when wash_out is used inside of a Rails engine

### ISSUE THREAD

**Issue by yjukaku** [inossidabile/wash_out#201]
Using `wash_out :foo` route generator generates two routes when inside of a `Blorgh` engine:

```
/foo/wsdl
/foo/action
```

but because these routes are "named" by Rails as `foo_wsdl` and `foo_action`, this gem can't find them because it will look for `blorgh_foo_action_url` when generating the WSDL.

Relevant lines:

https://github.com/inossidabile/wash_out/blob/master/lib/wash_out/dispatcher.rb#L75
and
 https://github.com/inossidabile/wash_out/blob/master/app/views/wash_out/rpc/wsdl.builder#L65

**Comment by inossidabile** [comment]
Indeed. I'm not sure if I will have time to watch this soon though. Will try to ASAP.

**Comment by bogdanRada** [comment]
I think the dirty fix would be to replace this line from dispatcher:
```ruby
 @name      = controller_path.gsub('/', '_')
```
with 
```ruby
 @name      = @namespace.gsub('/wsdl', '/action')
```

And in the view to use instead of this line:
```ruby
 xml.tag! "soap:address", :location => send("#{@name}_action_url")
```
This line

```ruby
  xml.tag! "soap:address", :location => "#{@name}"
```


This way having engine mounted at "/test" and having a controller named "client"
```ruby
  mount Client::Engine => '/test'
```
The namespace would be "/test/client/wsdl" . Which works. 

Let me know what you think. I already tested this and for me it works.

**Comment by bogdanRada** [comment]
Awesome :+1:

**Comment by yjukaku** [comment]
I don't think the changes proposed by @bogdanRada were applied correctly.  Trying the latest gem in a new engine fails on the same line (Line #65 of `wsdl.builder`).

**Comment by bogdanRada** [comment]
Actually my proposal was totally wrong. @inossidabile  found a much better way, And for me it works. You can even test it here: https://washout-builder.herokuapp.com/ , and the souce code is here https://github.com/bogdanRada/washout_builder_demo . You can try in interface the "Client" related links.

**Comment by bogdanRada** [comment]
But i am really curious though if you're using engines in some other way. I might need to patch my own gems too for that.

**Comment by yjukaku** [comment]
Ah, it looks like you are using the `module: 'engine_name'` option in your engine's `routes.rb`.  I didn't realize that was necessary.

However, on a related note, using a namespace *inside* of an engine doesn't seem to be possible. For example, if inside of an engine you want to create a namespace "soapapi"

`/myengine/soap_api/products/wsdl`

``` ruby
Myengine::Engine.routes.draw do
	namespace :soap_api do
		wash_out "products"
		wash_out "products", module: "Myengine" #also doesn't work
	end
end

```

**Comment by bogdanRada** [comment]
i was able to find a way to make it work: 
```
Myengine::Engine.routes.draw do
    scope "/soap_api" do
        wash_out "products"
        wash_out "products", module: "Myengine" 
    end
end
```

You can check it here: https://washout-builder.herokuapp.com/. I just added a new engine to the application (engine2) . 

Not sure though what is the difference between using a "scope" and a "namespace".

**Comment by yjukaku** [comment]
Namespaces are used when you want to add something to the routes AND also require a module (so in this case, with a namespace, the `ProductsController` would look like:

```
module Myengine
  module SoapApi
    class ProductsController
      #...
    end
  end
end
```

Whereas a `scope` just adds to the path but doesn't change anything else.

The solution you mentioned above will indeed help you to add the `/soap_api/`to the beginning of the route, but you lose the module namespacing that you'd want if you used a namespace.

**Comment by bogdanRada** [comment]
yeah, i know that difference. I meant not sure why is working with scopes but not with namespace. Bad english, sorry.

**Comment by bogdanRada** [comment]
if i use though my dirty fix works. But not sure if that's ok.

**Comment by bogdanRada** [comment]
The latest master seems to break also namespaces even if not inside an engine, which was working before these changes. you can check it here: https://washout-builder.herokuapp.com/ , if you click on Api::Rumbas or Api::ProjectService on links to generate wsdl , that is not working anymore with latest master. 

I use this routes:
```ruby 
Rails.application.routes.draw do

  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
  namespace :api do
    wash_out :rumbas,  module: 'Api'
    wash_out :project_service,  module: 'Api'
  end

   # etc ...
end
```

I only noticed this while testing some otther changes.

**Comment by bogdanRada** [comment]
Here's another alternative, that will get all the routes available including the engines routes, 
it finds the engine that has the corresponding route specific for that controller, 
and uses the RouteSet of the engine to have access to the **url_helpers** on the engine, and then calls **url_for** to generate the links.  I am using similar code in my own gem https://github.com/bogdanRada/washout_builder and it works. 

The usage would be fairly simple. You can just put this code in Dispatcher and only call method "get_controller_uris" where you need them, since the Dispatcher has access to "controller_name" method from ActionController::Base. 

```ruby


def find_all_routes
  engines = [Rails.application]
  engines.concat(::Rails::Engine.subclasses)

  routes = engines.each_with_object([]) do |engine, routes_array|
    engine_route = Rails.application.routes.named_routes[engine.engine_name]
    routes_hash_array = engine.routes.routes.map { |route|
      {
        engine: engine,
        route_set: engine.routes,
        route: route,
        mounted_at: engine_route.blank? ? nil : engine_route.path.spec.to_s
      }
    }

    routes_array.concat(routes_hash_array)
  end

  routes
end

def route_can_generate_wsdl?(route)
  route.defaults[:action] == "_generate_wsdl"
end

def find_controller_route(controller)
  find_all_routes.find do |hash|
    hash[:route].present? && route_can_generate_wsdl?(hash[:route])
  end
end

def route_helpers(hash)
  hash[:route_set].url_helpers
end

def service_wsld_url(hash, controller_name)
  route_helpers(hash).url_for(controller: controller_name, action: "_generate_wsdl", only_path: true)
end

def service_endpoint(hash, controller_name)
  # TODO: haven't figure out yet how to use url_for with WashOut::Router middleware , so for now i am using gsub as an alternative
  service_namespace(hash, controller_name).gsub('/wsdl', '/action')
end

def get_controller_uris
  route_details = controller_is_a_service?(controller_name)
  if route_details.present?
    {
      wsdl_uri: service_wsld_url(route_details, controller_name),
      endpoint_uri: service_endpoint(route_details, controller_name)
    }
  end
end


```

It might be though a better alternative, but wanted to post this also in case it might be helpful.

**Comment by inossidabile** [comment]
@yjukaku please try this build. You lost my sunday :)

**Comment by inossidabile** [comment]
Btw, I dropped that `:module` crap. It's now inherited from the routes properly. Remove it or you will proxy that to Rails as-is and that's not really what you need if you have namespaces according to convention.

**Comment by bogdanRada** [comment]
I get a error "Undefined method path for nil:Nilclass " in WashOut::Router in method sefl.url when i try to see the WSDL from an engine. This is happenning because you only use Rails.application.routes to go through them, but you're not going through engines routes.

You need to do this:
```
engines = [Rails.application]
 engines.concat(::Rails::Engine.subclasses)

engines.each do |engine|
 engine.routes.routes..select do |x| 
  .....do your stuff....
end
end.first
```

**Comment by bogdanRada** [comment]
Also it seems now the action URL is not accesible from a engine, because the Washout::Router gets initialized with only the controller name without having the engine name as a namespace.  But this i think is because of the missing changes in the ActionDispatch::Routing::Mapper. I am not sure though,

**Comment by inossidabile** [comment]
Good catch, @bogdanRada. I made it traverse engines routes recursively. What's for "EDIT 2": that's probably your misunderstanding of Rails routes. The problem you are describing isn't related to WashOut. We don't even handle this `module` ourselves anymore. When you use `scope` like that - it's just a generally wrong way for Rails and it breaks on level of Rails router (scope makes it loose the module inheritance - that's why setting it manually fixes things back)

**Comment by bogdanRada** [comment]
Thanks, now is working ok.

About the "EDIT 2" , you can check here: https://github.com/bogdanRada/washout_builder_demo/blob/master/engines/my_engine2/config/routes.rb 

I have this configuration for that engine:

```ruby
Namespace::MyEngine2::Engine.routes.draw do
  scope '/soap_api' do
    wash_out :test_engine2, module: "namespace/my_engine2"
  end
end
```

If i don't put the module option, when i run ```bundle exec rake routes``` , i can see this routes:

```bash
Routes for Namespace::MyEngine2::Engine:
    test_engine2_wsdl GET      /soap_api/test_engine2/wsdl     namespace/my_engine2/test_engine2#_generate_wsdl
    test_engine2_soap GET|POST /soap_api/test_engine2/action   #<WashOut::Router:0x000000030f5e08 @controller_name="TestEngine2Controller"> {:defaults=>{:controller=>"test_engine2", :action=>"soap"}}
```

As you can see, the WashOutRouter gets  instantiated with controller_name "TestEngine2Controller"


But if i leave the module option, i can see the correct routes:

```bash
Routes for Namespace::MyEngine2::Engine:
    namespace_my_engine2_test_engine2_wsdl GET      /soap_api/test_engine2/wsdl     namespace/my_engine2/test_engine2#_generate_wsdl
    namespace_my_engine2_test_engine2_soap GET|POST /soap_api/test_engine2/action   #<WashOut::Router:0x00000003308b00 @controller_name="Namespace::MyEngine2::TestEngine2Controller"> {:defaults=>{:controller=>"namespace/my_engine2/test_engine2", :action=>"soap"}}
```

**Comment by inossidabile** [comment]
`0.11.0.beta.2` released. Closing.

**Comment by inossidabile** [comment]
You do use scope wrong, yes.

**Comment by bogdanRada** [comment]
Yep. I thought so :) Thanks for being so patient with me :) and thank you very much for this great work . This is awesome :)
