### ISSUE TITLE
SOAP Errors don't render SOAP Fault?

### ISSUE THREAD

**Issue by yjukaku** [inossidabile/wash_out#204]
As far as I can tell, the standard on a SOAP error is to render a SOAPFault message. [W3 SOAP 1.2 SOAP Fault Spec](https://www.w3.org/TR/soap12-part1/#soapfault)

Currently, raising a SOAPError from a WashOut controller action just results in a 500 error and a backtrace, which actually won't render anything to the client. This breaks rspec request specs, (you have to resort to 

```ruby
expect(post "my_action", xml_data).to raise_error
```

instead of

```ruby
post "my_action", xml_data
expect(response).to_not be_success
```

And of course, you can't test if the error messages given back are correct since there are none. Would wash_out want to offer standard SOAP Fault messages? Here's an example of a SOAP Fault from the MSDN docs for SQL Server (https://msdn.microsoft.com/en-us/library/ms189538(v=sql.105).aspx)

**Comment by inossidabile** [comment]
But that's not true. Look: https://github.com/inossidabile/wash_out/blob/master/spec/lib/wash_out_spec.rb#L543. We do intercept this exception and we do show proper XML output according to standard. If there's a case where it doesn't work - you need to show me how to reproduce it.
