### ISSUE TITLE
wash_out references Rails classes without requiring or depending on them

### ISSUE THREAD

**Issue by JasonBarnabe** [inossidabile/wash_out#219]
https://github.com/inossidabile/wash_out/blob/master/lib/wash_out.rb references all sorts of Rails classes, but they are never `require`d and are not listed as dependencies for the gem. I'm guessing the specs for the gem work because rspec-rails requires railties, which brings everything in. 

This is causing me problems in my gem [qbwc](https://github.com/qbwc/qbwc) when I run tests with Rails 5 because I'm not including action_view.

I imagine `require`ing railties and adding it as a runtime dependency would fix it, but I'm not sure if you want to do that or be more selective in what's brought in.

**Comment by inossidabile** [comment]
It was exactly for the sake of not including excessive stuff. WashOut lasts for many rails versions and I'm not sure having this kind of dependency is a good idea. For instance, if you are not including `action_view` - you are doing it on purpose. Is that a good idea to silently include it without any notification? I'm not so sure.

**Comment by JasonBarnabe** [comment]
As it is currently, if you don't have `action_view`, then [things fail](https://travis-ci.org/qbwc/qbwc/jobs/184444950). Based on your comment, I would suggest that wash_out check to see if `action_view` is around before [using it](https://github.com/inossidabile/wash_out/blob/a40129f58a8c0145cb98853daa892807735fb910/lib/wash_out.rb#L65), like what happens with [ActiveRecord](https://github.com/inossidabile/wash_out/blob/a40129f58a8c0145cb98853daa892807735fb910/lib/wash_out.rb#L41). I can prepare a PR if you agree.

There are probably other things that someone might not have installed, but I'm not sure what combinations make any sense. In any case, it's just `action_view` that I'm hung up on.

**Comment by inossidabile** [comment]
I think it should raise understandable exception if you don't have it installed. So you understand what's happening and can fix it on your own. Such PR I will accept gladly.

**Comment by JasonBarnabe** [comment]
Having a dependency enforced at runtime doesn't make any sense. Either:

a) wash_out requires action_view, so it should be in the gemspec, or
b) action_view is optional for wash_out, so it should work without it.

I've gone with B and created PR #223.
