### ISSUE TITLE
List Object to Return

### ISSUE THREAD

**Issue by joseneto** [inossidabile/wash_out#220]
Hi,

How can I return a simple list?

I need return this:
`<fornecedores>
 <fornecedor>
 <LIFNR>SAP 0000008207</LIFNR>
 <STKZN>PF</STKZN>
 <LOEVM>ativo</LOEVM>
 <NAME1>JOAO DA SILVA</NAME1>
 </fornecedor>
  <fornecedor>
 <LIFNR>SAP 0000008207</LIFNR>
 <STKZN>PF</STKZN>
 <LOEVM>ativo</LOEVM>
 <NAME1>JACK MINEST</NAME1>
 </fornecedor>
</fornecedores>`

My actual xml:
`<fornecedores>
 <fornecedor>
 <LIFNR>SAP 0000008207</LIFNR>
 <STKZN>PF</STKZN>
 <LOEVM>ativo</LOEVM>
 <NAME1>JOAO DA SILVA</NAME1>
 </fornecedor>
 </fornecedores>
 <fornecedores>
  <fornecedor>
 <LIFNR>SAP 0000008207</LIFNR>
 <STKZN>PF</STKZN>
 <LOEVM>ativo</LOEVM>
 <NAME1>JACK MINEST</NAME1>
 </fornecedor>
</fornecedores>`

Return setup:
`:return => {:fornecedores => [:fornecedor =>{
                                                'LINFR' => :string,
                                                'LOEVM'  => :string,
                                                'NAME1'  => :string,
                                                'STKNZ' => :string}]}`

Anyone can help me?

**Comment by joseneto** [comment]
Sorry, I figure out change the return to string, and send a xml

**Comment by jdsampayo** [comment]
close the issue?

**Comment by joseneto** [comment]
Sure.

**Comment by nikita3915** [comment]
Hi, 
Can you help me ? How can I return array of Active Record objects
This code returns one object
`  
soap_action 'get_products',
  :return => [Product]
  def get_products
    render soap: [Product.last.as_json]
  end
`
result:
`{:get_products_response=>
  {:value=>
    {:id=>"3",
     :title=>"Rails Test Prescriptions",
     :description=>
      "Test description",
     :image_url=>"rtp.jpg",
     :price=>"34",
     :created_at=>"2016-07-21 21:33:25 UTC",
     :updated_at=>"2016-07-21 21:33:25 UTC",
     :"@xsi:type"=>"tns:product"}}}
`
How can I return a few these objects ? 
`render soap: [Product.limit(3)]`

**Comment by xeviercr4** [comment]
Hello, I have the same initial problem that @joseneto.

How went the solution? Will you pass-me your array declaration?

Thanks.
