### ISSUE TITLE
Builder without "tns:" response prefix?

### ISSUE THREAD

**Issue by cmdrkeene** [inossidabile/wash_out#224]
The file `app/views/wash_out/document/response.builder` forces the `tns:` prefix within `<soap:Body>` child elements, even with the `:response_tag` configured.

The specs I were given for this project want a SOAP Body like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> <soap:Body>
<ota:OTA_ProfileReadRS xmlns:ota="http://www.opentravel.org/OTA/2003/05"> <ota:Success/>
<ota:Profiles>
    <ota:ProfileInfo>
<ota:UniqueID ID="111240578" Type="21"/>
     ...
    </ota:ProfileInfo>
  </ota:Profiles>
 </ota:OTA_ProfileReadRS>
 </soap:Body>
</soap:Envelope>
```

Is this possible with `wash_out`?

Will SOAP clients handle the indirection of `xmlns:tns="ota"` and `tns:` prefixed tags?

This world of SOAP is scary and baroque, any pointers are appreciated.

**Comment by inossidabile** [comment]
It is possible. Copy this WSDL, edit it, make accessible, ready. WSDL isn't forced to be auto-generated. You can make your own copy.

**Comment by cmdrkeene** [comment]
No idea how to use my own WSDL versus using the auto-generated one, and we're clearly not on the same page here, so I'm going not use this gem because it's too confusing. Thanks!
