### ISSUE TITLE
Difference of /wsdl and /action ?

### ISSUE THREAD

**Issue by pedrocaseiro** [inossidabile/wash_out#226]
I just deployed my app to heroku and I have the 2 following ur'ls:

```
https://nourish-huginn.herokuapp.com/true_kare/action
https://nourish-huginn.herokuapp.com/true_kare/wsdl
```

I'm using postman to make SOAP requests. The request works for the first url (/action) but not for the second one (/wsdl). Althought, if I go to both of the url's in my browser, the first one (/action) renders a Invalid SOAP Request and the second one (/wsdl) renders the WSDL properly.

Is this the normal behavior?

**Comment by inossidabile** [comment]
Please read how you should use SOAP. Normally you feed wsdl url to client and start from there.
