### ISSUE TITLE
Option for defining a custom SOAP service name

### ISSUE THREAD

**Issue by jesusabarca** [inossidabile/wash_out#242]
As required by the company consuming our web service, we needed to change the name of the SOAP service from:
```xml
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:WashOut" ...>
  ...
  <service name="service">
    ...
  </service>
</definitions>
```
to:
```xml
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:WashOut" ...>
  ...
  <service name="CustomServiceName">
    ...
  </service>
</definitions>
```

**Comment by nbarthel** [comment]
+1 - I need this also

**Comment by sateeshkulla** [comment]
I need this too..can you merge the PR

**Comment by rohanmendon** [comment]
need this too

**Comment by rohanmendon** [comment]
@jesusabarca since your PR hasnt been merged yet, did you find a workaround ?

**Comment by jesusabarca** [comment]
@rohanmendon sorry for the late response. I did not find a workaround. We had to fork this repo (at work) and point out gemfile to that repo instead 🙃.

It might be a good time for starting a new project forking this gem. Any one interested in joining in?

**Comment by ramanbuttar** [comment]
@jesusabarca  I am interested in forking this project and continuing development. 
I'll be helping with rewriting our existing webservices written in ColdFusion with a SOAP/XML interface using Ruby 2.4.1 and Rails 5.1 and this gem will be crucial for the replatforming project.

**Comment by jesusabarca** [comment]
@ramanbuttar cool, I'll create the fork, I just need to double check the license thingy
