### ISSUE TITLE
Please release 0.12.0 of gem

### ISSUE THREAD

**Issue by lostapathy** [inossidabile/wash_out#245]
Please release 0.12.0 of this gem to rubygems so that downstream issues such as https://github.com/qbwc/qbwc/pull/117 can be worked through.  The gemspec has already been updated for that version.

If there are other action items before this can happen, please let me know - I am happy to help work through them.

Thanks @inossidabile !

**Comment by inossidabile** [comment]
Done

**Comment by lostapathy** [comment]
Thanks @inossidabile !
