### ISSUE TITLE
HTTPS protocol

### ISSUE THREAD

**Issue by mr-koww** [inossidabile/wash_out#253]
Can this gem works with https protocol? When I try connect, but request go to http :(
![2018-04-10_16-10-37](https://user-images.githubusercontent.com/6480930/38558910-495664b4-3cda-11e8-91b4-9f55b3460eab.png)

**Comment by cmager** [comment]
hi, I am using an nginx proxying to unicorn.
I got to manage this by adding a header like this:

```nginx
location /some/endpoint {
  proxy_redirect off;
  proxy_pass http://rails-app/internal/enpoint;
  ...
  proxy_set_header X-Forwarded-Proto $scheme; ### <---
}
```
