### ISSUE TITLE
Receive attachments with wash_out

### ISSUE THREAD

**Issue by josephbhunt** [inossidabile/wash_out#262]
I'm struggling to understand how I can get washout to produce a wsdl that defines how an endpoint should consume an image attachment. I'm using soap-ui to manually test. According to the soap-ui docs the wsdl should define SWA or swaREF attachments. How can I do that in washout?

SoapUi docs. https://www.soapui.org/docs/soap-and-wsdl/attachments.html

**Comment by josephbhunt** [comment]
@inossidabile Does wash_out even support generating a wsdl that defines a multipart mime type? I've been looking through it in the code and I can't find it.

**Comment by inossidabile** [comment]
It's not supported, no.
