### ISSUE TITLE
WashOut::Type correct usage

### ISSUE THREAD

**Issue by foton** [inossidabile/wash_out#59]
Hi, i trying to redo my existing "actionwebservice" SOAP service in Rails 2 to Rails 3 with "wash_out".
Original Rails 2 WSDL is at the end.

I have problem to correctly setup model 

```
 Lead < WashOut::Type
    map {:id => :integer, :rodne_cislo => :string, :email => :string}
 end
```

to have accesible attributes ("rodne_cislo","email" ....), which I can use in other controllers and models.
The "actionwebservice" have for this purpose method "member", which defined virtual atribute with accessors.

```
  member :id, :int
  member :rodne_cislo, :string
```

Can somebody point me on solution?

WSDL I woul like to implement is:

```
<definitions name="Soap" targetNamespace="urn:ActionWebService">
   <types>
     <xsd:schema targetNamespace="urn:ActionWebService">

       <xsd:complexType name="Lead">
         <xsd:all>
           <xsd:element name="shoda_adres" type="xsd:int"/>
           <xsd:element name="note" type="xsd:string"/>
           <xsd:element name="rodne_cislo" type="xsd:string"/>
           <xsd:element name="ulice_nem" type="xsd:string"/>
           <xsd:element name="provize_za_smlouvu" type="xsd:double"/>
           <xsd:element name="zdroj_kontaktu" type="xsd:string"/>
           <xsd:element name="email" type="xsd:string"/>
           <xsd:element name="ulice_kontk" type="xsd:string"/>
           <xsd:element name="typ_uveru" type="xsd:int"/>
           <xsd:element name="status" type="xsd:int"/>
           <xsd:element name="cislo_nem" type="xsd:string"/>
           <xsd:element name="errors" type="typens:StringArray"/>
         </xsd:all>
       </xsd:complexType>

       <xsd:complexType name="StringArray">
          <xsd:complexContent>
              <xsd:restriction base="soapenc:Array">
                <xsd:attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:string[]"/>
             </xsd:restriction>
         </xsd:complexContent>
        </xsd:complexType>

    </xsd:schema>
  </types>

  <message name="ShowLead">
    <part name="id" type="xsd:int"/>
    <part name="poradce" type="xsd:string"/>
  </message>

  <message name="ShowLeadResponse">
    <part name="return" type="typens:Lead"/>
  </message>

 <message name="AddLead">
   <part name="lead" type="typens:Lead"/>
 </message>

 <message name="AddLeadResponse">
   <part name="return" type="typens:Lead"/>
 </message>

<portType name="SoapSoapPort">

  <operation name="ShowLead">
    <input message="typens:ShowLead"/>
    <output message="typens:ShowLeadResponse"/>
  </operation>

  <operation name="AddLead">
    <input message="typens:AddLead"/>
    <output message="typens:AddLeadResponse"/>
  </operation>

 </portType>

 <binding name="SoapSoapBinding" type="typens:SoapSoapPort">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>

       <operation name="ShowLead">
           <soap:operation soapAction="/soap/api/ShowLead"/>
           <input>
              <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
           </input>
           <output>
                <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
      </operation>

      <operation name="AddLead">
        <soap:operation soapAction="/soap/api/AddLead"/>
            <input>
                <soap:body namespace="urn:ActionWebService" use="encoded"         encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>

    </binding>

    <service name="SoapService">
        <port name="SoapSoapPort" binding="typens:SoapSoapBinding">
            <soap:address location="https://data.smartcorporation.cz/soap/api"/>
        </port>
    </service>

</definitions>
```

**Comment by julianog12** [comment]
Hi foton,

Did you find a solution to port your wsdl to rails 3 or 4?

**Comment by inossidabile** [comment]
@julianog12 do no try to reproduce the WSDL with WashOut. Instead just expose the existing WSDL fixing endpoints to refer to WashOut controllers. It should work - WashOut isn't too strict when it receives a request.

**Comment by julianog12** [comment]
Hi inossidabile,

i tried to generate this:

<complexType name="KitProduto">
<sequence>
<element maxOccurs="1" minOccurs="0" name="codRet" type="xsd:int"/>
<element maxOccurs="1" minOccurs="0" name="MsgRet" nillable="true" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="CodProduto" nillable="true" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="NomProduto" nillable="true" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="CMP" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="CMPObrig" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="Coberturas" nillable="true" type="xsd:string"/>
<element maxOccurs="1" minOccurs="0" name="CMPAjuda" type="xsd:string"/>
</sequence>
</complexType>
<complexType name="KitProdutoArray">
<complexContent>
<restriction base="soapenc:Array">
<attribute ref="soapenc:arrayType" wsdl:arrayType="tns1:KitProduto[]"/>
</restriction>
</complexContent>
</complexType>

**Comment by inossidabile** [comment]
You shouldn't generate nothing. The chance to repeat WSDL 1-1 is exactly zero. Just use your WSDL as-is and try to repeat it at WashOut as close as possible. Then route queries from your WSDL to WashOut controllers.

**Comment by julianog12** [comment]
I can not understand

**Comment by julianog12** [comment]
my cod:

class Parametro < WashOut::Type
      type_name "ParametroArray"
	  map :Parametro => {:nome => :string, :valor  => :double}
  end
  
  class ParametroArray < WashOut::Type
	map :Parametro => Parametro
  end

**Comment by julianog12** [comment]
my english is very bad!!
